# Generated by Django 3.0.9 on 2021-12-12 04:21

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Country',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=60)),
                ('countrycode', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='Capital',
            fields=[
                ('name', models.CharField(max_length=60)),
                ('state', models.CharField(max_length=60)),
                ('country', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, serialize=False, to='app.Country')),
            ],
        ),
    ]
